### ISSUE TITLE
Dynamic code execution is always an issue and should never be used.

### ISSUE THREAD

**Issue by KOLANICH** [JarryShaw/PyPCAPKit#107]
**Describe the bug**
The library contains `exec` call

**System information**
A clear and concise description of your system information.
 - OS Version: any
 - Python Version: any
 - Python Implementation:any

**Traceback stack**
Was not executed.

**Expected behavior**
Must not contain any dynamic code execution.

**Additional context**
Dynamic code execution is [always a security issue](https://github.com/Bitmessage/PyBitmessage/commit/8ce72d8d2d25973b7064b1cf76a6b0b3d62f0ba0#diff-54d55baf8967b2416bd9fc199d3cc22dcf68d95aeeb45f447bf8b0b0bf662b8fR9).

**Comment by JarryShaw** [comment]
Thanks for reporting. The `exec` call was inevitable to implement [`pcapkit.corekit.infoclass.Info`](https://github.com/JarryShaw/PyPCAPKit/blob/master/pcapkit/corekit/infoclass.py#L51-L120), which is actually borrowed from Python's built-in module [`dataclasses`](https://github.com/python/cpython/blob/3.10/Lib/dataclasses.py#L434).

**Comment by KOLANICH** [comment]
Thanks for the info. I could never imagine that this kind of code could ever land into the standard library.

https://github.com/python/cpython/issues/93452
