### ISSUE TITLE
Reassembly not working since 0.16.3

### ISSUE THREAD

**Issue by newinnovations** [JarryShaw/PyPCAPKit#155]
**Describe the bug**
The example for reassembly in the documentation and `test/test_reassembly.py` do not work for the 1.x.x versions. Latest working version seems to be 0.16.3.

**System information**
A clear and concise description of your system information.
 - OS Version: Ubuntu 22.04.3 LTS
 - Python Version: Python 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0] on linux
 - Python Implementation: CPython

**Traceback stack**
```text
$ PCAPKIT_DEVMODE=true python3 test_reassembly.py
/home/martin/edc/network/.venv/lib/python3.11/site-packages/pcapkit/__init__.py:0: DevModeWarning: development mode enabled
  PCAPKIT_DEVMODE=true
Frame   1: Ethernet:IPv4:TCP
Frame   2: Ethernet:IPv4:TCP
Frame   3: Ethernet:IPv4:TCP
Frame   4: Ethernet:IPv4:TCP:Raw
..snip..
Frame 744: Ethernet:IPv4:TCP:Raw
Frame 745: Ethernet:IPv4:TCP
Frame 746: Ethernet:IPv4:TCP:Raw
Traceback (most recent call last):
  File "/home/martin/edc/network/PyPCAPKit/test/test_reassembly.py", line 19, in <module>
    for datagram in extraction.reassembly.tcp:  # type: ignore[union-attr]
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/martin/edc/network/.venv/lib/python3.11/site-packages/pcapkit/foundation/extraction.py", line 227, in reassembly
    data = ReassemblyData(
           ^^^^^^^^^^^^^^
NameError: name 'ReassemblyData' is not defined. Did you mean: 'ReassemblyManager'?
```
**Expected behavior**
No error, working tests.

**Additional context**
`test/test_reassembly.py` relies on `../sample/test.pcap` which does not exist. I provided my own `test.pcap`. 

`test/` directory seems to be more like examples than tests. Might be worth creating a unit test set, or at least check manually that the examples are still working. Another non-working example is `test/test_http.py` which relies on  `../sample/http.pcap` that also does not exist.

**Comment by JarryShaw** [comment]
As of version `1.0.0`, PyPCAPKit reconstructed its internal data models and several breaking changes were made to better support the expansion of the code base. This import error has now been fixed in version **`1.1.1`**. Thanks for reporting.
