### ISSUE TITLE
ipv6 packet with option decodes error

### ISSUE THREAD

**Issue by h3cnp** [JarryShaw/PyPCAPKit#218]
**Describe the bug**
An IPv6 packet with option decodes error

**System information**
A clear and concise description of your system information.
 - OS Version: win10
 - Python Version: 3.11
 - Python Implementation: [e.g. CPython, PyPy]

**Traceback stack**
>>> pcapkit.PCAPKIT_DEVMODE=True
>>> json = pcapkit.extract(fin='ipv4_over_srv6.pcap', fout='out.json', format='json', extension=False)
[ERROR] 06/24/2024 03:36:43 PM - bad char in struct format
struct.error: bad char in struct format
[WARNING] 06/24/2024 03:36:43 PM - EOF reached
>>>
>>> json = pcapkit.extract(fin='sbfd.pcap', fout='out.json', format='json', extension=False)
[WARNING] 06/24/2024 03:37:19 PM - EOF reached
>>>
[frame.zip](https://github.com/user-attachments/files/15951387/frame.zip)

**Expected behavior**
L4 header (e.g. UDP) or tunnel payload after IPv6 option decodes error. It looks like L4 parsing starts from the ipv6 option.
Find the example packet in the attachment.

**Additional context**

**Comment by JarryShaw** [comment]
It appears that the padding length of the capsulated IPv4 packet was incorrectly calculated (as `-4`). I'll look further into this issue.

**Comment by JarryShaw** [comment]
This issue should've been fixed in **PyPCAPKit 1.3.4**.
