### ISSUE TITLE
'bs4' dependency not installed via pip

### ISSUE THREAD

**Issue by tsellon** [JarryShaw/PyPCAPKit#31]
**Describe the bug**
After installing the latest release using "pip install pypcapkit" into a virtualenv, I get the following "module not found" error when importing pcapkit:
ModuleNotFoundError: No module named 'bs4'

Running "pip install bs4" resolves this.

**System information**
A clear and concise description of your system information.
 - OS Version: macOS High Sierra 10.13.6
 - Python Version: 3.6.5
 - Python Implementation: CPython

**Comment by tsellon** [comment]
Not a huge issue, but wanted to make sure it got logged. Thanks for creating this!

**Comment by JarryShaw** [comment]
Thanks for your report. ❤️

**Comment by JarryShaw** [comment]
Will be fixed in v0.14.5

Should you wish to use `pcapkit.vendor` utilities, please installed PyPCAPKit with `pcapkit[vendor`.
