### ISSUE TITLE
C Arrays Format Parser

### ISSUE THREAD

**Issue by DolevAttiya** [JarryShaw/PyPCAPKit#32]
Hello,
It will be nice if the module could parse as in "C Arrays" format from a TCP / UDP Stream (as Wireshark give this feature in the GUI version, adding photos).

[https://imgur.com/a/rpEnkLB](url)
 
Thank you for your help :)

**Comment by JarryShaw** [comment]
You may simply create a C Array parser to convert each peer array as *bytes* or *bytesarray*, and supply to the protocol parser of PyPCAPKit.

There is no need to bundle specifically a C Array parser in PyPCAPKit. 

Thx for your issue.
