### ISSUE TITLE
packet.analyse() fails: UnicodeDecode error

### ISSUE THREAD

**Issue by deepak-sankey** [JarryShaw/PyPCAPKit#33]
**Describe the bug**
Showing error 'charmap' codec can't decode byte 0x81

**Environment information**
Python: 3.8.0

**Traceback stack**
Traceback (most recent call last):
  File "pcapkit-demo.py", line 8, in <module>
    analysis = pcapkit.analyse(fileObj, length=None)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 205: character maps to <undefined>

**Expected behavior**
It should analyze the packets

**Additional context**
deepak.t@sankeysolutions.com
+91 8097872267

**Comment by JarryShaw** [comment]
Cloud you please supply your environment information? `charmap`  doesn't seem like a regular codec to me.

**Comment by deepak-sankey** [comment]
Updated environment information

**Comment by JarryShaw** [comment]
Well... if you would provide the content of `fileObj` (both source code and PCAP file if possible) and the full traceback stack with environment variable `PCAPKIT_DEVMODE =1`, I will be able to dig into it.

Like I said, `charmap` is not a regular codec to me and I should have caught all `UnicodeDecodeError` at `pcapkit.protocols.protocol.Protocol.decode`. So, I need more information to see what's exactly going on :)

**Comment by JarryShaw** [comment]
Closing this issue since no response for long time.
