### ISSUE TITLE
pcapkit-vendor causes PermissionError writing to site-packages

### ISSUE THREAD

**Issue by jayvdb** [JarryShaw/PyPCAPKit#38]
pcapkit-vendor causes a write to site-packages, which should be read-only, and is read-only on distro.

**System information**
Using https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pypcapkit
Python 3.8

**Traceback stack**
```py
/usr/bin/pcapkit-vendor
Ethertype IEEE 802 Numbers
Operation Codes [RFC 826][RFC 5494]
ESP Transform Suite IDs
Cipher IDs
HIP NAT Traversal Modes
Registration Types
HTTP/2 Error Code
Option Classes
IPv4 Router Alert Option Values
TOS (DS Field) Reliability
QS Functions
TaggerID Types
Authentication Types
Priority levels defined in IEEE 802.1p.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pcapkit/vendor/__main__.py", line 30, in run
    vendor()
  File "/usr/lib/python3.8/site-packages/pcapkit/vendor/default.py", line 243, in __init__
    with open(os.path.join(ROOT, '..', 'const', STEM, FILE), 'w') as file:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/pcapkit/vendor/../const/hip/cipher.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/lib/python3.8/site-packages/pcapkit/vendor/__main__.py", line 32, in run
    warnings.warn(error, VendorRuntimeWarning)
TypeError: expected string or bytes-like object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/pcapkit-vendor", line 11, in <module>
    load_entry_point('pypcapkit==0.14.5', 'console_scripts', 'pcapkit-vendor')()
TypeError: expected string or bytes-like object
```

**Expected behavior**
If there is a need to write custom code to the site-packages, that should be done in setup.py

**Comment by JarryShaw** [comment]
The `pcapkit-vendor` is not intended for calling by normal user. This executable was bundled just for administrators to update the constant enumerations in `pcapkit.const` package, since I may not update them quite in time. Therefore, it is not to be done in the `setup.py` and it will require `sudo` privileges if needed to update the files.

Also, I noticed there was a `TypeError`. The bugfix is now under construction. New version of `pcapkit` with all stuff revised is on schedule. Please be patient.

**Comment by jayvdb** [comment]
Thank for the explanation.

Perhaps emit a notice in setup.py that `pcapkit-vendor` may be run to update `pcapkit.const`.  I expect packages would want to run it while building their rpms/debs/etc.

**Comment by JarryShaw** [comment]
I might integrate a command to make `pcapkit-vendor` running from `setup.py install`, but I dont think its necessary. Should you wish to run it while building, please contact corresponding maintainers and utilise the *postinstall* hooks if applicable.
