### ISSUE TITLE
Comma "," appears when parsing from pcap to JSON

### ISSUE THREAD

**Issue by normchri** [JarryShaw/PyPCAPKit#40]
Hi,
IN a Python3 program, I parse multiple pcap file in JSON using :
```
for ip in ip_list:
pcap_to_json = pcapkit.extract(fin=(ip+".pcap"), fout=(ip+"out.json"), format='json', extension=False)
```
**Describe the bug**
After the first file (10.10.0.51 in annexe) all the JSON files have a "," added at the second line which is not supposed to happen.

**Expected behavior**
no comma in the second line of JSON files

**Additional context**
Here is a zip containing examples:
[scan_21-05-2020_15-14-13.zip](https://github.com/JarryShaw/PyPCAPKit/files/4668042/scan_21-05-2020_15-14-13.zip)

**System information**
 - OS Version: Ubuntu 20.04
 - Python Version: 3.8

Thank you for your help !

**Comment by JarryShaw** [comment]
Hi there, thanks for reporting this issue. But may I know which version of **DictDumper** and **PyPCAPKit** you're using?

**Comment by normchri** [comment]
Hi,
Here is the version used:
dictdumper                    0.7.0.post1
pypcapkit                     0.14.5

**Comment by JarryShaw** [comment]
Issue fixed as we upgrade DictDumper dependency in version 0.15.0

Thx for reporting to us.
