### ISSUE TITLE
Unable to execute pcapkit at all. 

### ISSUE THREAD

**Issue by TonyCrespoMe** [JarryShaw/PyPCAPKit#46]
**Describe the bug**
After installing through pip or through git, trying to run the command "pcapkit" gives a "permission denied" error. Attempting to run it with elevated credentials gives a "command not found"

**System information**
A clear and concise description of your system information.
 - OS Version: macOS Mojave 10.14.6
 - Python Version:  3.7

**Expected behavior**
Run the script

**Additional context**
Have verified the correct path is added for the library.

**Comment by JarryShaw** [comment]
Hi there, first of all, thx for using PyPCAPKit.

To answer your issue, PyPCAPKit doesn't provide a `pcapkit` entrypoint, so i suppose you're talking about `pcapkit-vendor`, which is not intended for regular usage. 

Should you do wish to use `pcapkit-vendor`, it may require **root** privilege as you may have installed PyPCAPKit somewhere with **root** privilege. And when you run `sudo`, you'd better supply the absolute path to the `pcapkit-vendor` executable, as it may not be in the `PATH` environment of **root**.

**Comment by TonyCrespoMe** [comment]
> Hi there, first of all, thx for using PyPCAPKit.
> 
> To answer your issue, PyPCAPKit doesn't provide a `pcapkit` entrypoint, so i suppose you're talking about `pcapkit-vendor`, which is not intended for regular usage.
> 
> Should you do wish to use `pcapkit-vendor`, it may require **root** privilege as you may have installed PyPCAPKit somewhere with **root** privilege. And when you run `sudo`, you'd better supply the absolute path to the `pcapkit-vendor` executable, as it may not be in the `PATH` environment of **root**.

Hi JarryShaw, 

Thanks for your input. I was trying to use the CLI as shown in the readme document. 

####
$ pcapkit --help
usage: pcapkit [-h] [-V] [-o file-name] [-f format] [-j] [-p] [-t] [-a] [-v]
               [-F] [-E PKG] [-P PROTOCOL] [-L LAYER]
               input-file-name

PCAP file extractor and formatted exporter

positional arguments:
  input-file-name       The name of input pcap file. If ".pcap" omits, it will
                        be automatically appended.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         show program's version number and exit
####

**Comment by JarryShaw** [comment]
Noted, just updated the README, what you're looking for is now renamed as `pcapkit-cli`.
