### ISSUE TITLE
How to obtain tpc trace flow

### ISSUE THREAD

**Issue by Dadigno** [JarryShaw/PyPCAPKit#65]
Hi, 
**Describe the bug**
I have been trying for a while to trace TCP flows using TraceFlow but without success.
I did so:
`
extractor = pcapkit.extract(fin='in.pcap', fout='out.json', format='json', extension=False, protocol='tcp', trace=True, trace_fout="trace_out")
`
but trace_out file is not created,  only out.json

**Expected behavior**
New file trace_out containing all TCP flows

**Additional context**
I attach the file in.pcap
[in.zip](https://github.com/JarryShaw/PyPCAPKit/files/5359166/in.zip)

Maybe I'm doing something wrong.
Can anyone provide me a simple example to do this operation?

Thx a lot

**Comment by JarryShaw** [comment]
Hi there, 

So first, I must apologise that the link layer protocol "cooked linux" is currently **NOT** supported by PyPCAPKit; however, as I tested, you can use Scapy engine:

```python
extractor = pcapkit.extract(
  fin='in.pcap', # input file
  fout='out.json', # output file
  trace=True, # enable TCP trace flow
  trace_fout="trace_out",  # trace flow output directory 
  trace_format='json',  # trace flow output format
  engine='scapy',  # use Scapy which supports the cooked linux link layer protocol
)
```

To recap, there're basically three problems:

1. PyPCAPKit doesn't support the link layer protocols, therefore cannot extract TCP packets from the PCAP file

**Solution**: use Scapy engine instead

2. `trace_format` parameter not provided, thus PyPCAPKit won't generate any output document

**Solution**: specify `trace_format` with your desired format

3. PyPCAPKit is not compatible with the latest version of Scapy

**Solution**: upgrade PyPCAPKit to the latest *0.15.5* release
