### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Ekultek** [JarryShaw/PyPCAPKit#73]
I just have a question, is it possible to use this to parse domains out of PCAP data?

**Comment by JarryShaw** [comment]
Well, ça depend if the parsing engines (PyPCAPKit built-in, Scapy, DPKT, PyShark) support the protocol where you would like to obtain the domains.

Would you wish to extract domains from HTTP request headers, then yes, you just need to look for the corresponding attributes from the returned HTTP protocol instance.

And in some cases you might need to operate on the reassembled TCP payload. Still, PyPCAPKit provides the parsed reassembled payload that you can use directly. Pls refer to the `interface` module and documentations for more information.

**Comment by Ekultek** [comment]
@JarryShaw awesome, thank you so much for your answer. Are you against us using this in a corporate setting as long as credit is reserved to you and the license is left intact?

**Comment by JarryShaw** [comment]
Sure. As long as you would be respecting the open source license of PyPCAPKit, you may use it at your own purpose.

Should you encounter any issue with PyPCAPKit, do pls submit to this repository. Thx for your appreciation on PyPCAPKit ;)

**Comment by Ekultek** [comment]
Will do, thanks

**Comment by Ekultek** [comment]
Also congrats on becoming apart of ![Malcore](https://penetrum.com/Penetrum-Security/Maltree)
